name: "react app deployment workflow"
on:
  push:
    branches:
      - main

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout the code"
        run: echo "checkout"
      